#--------------------------------------------------------------------------------------#
# AllCloud AWS LZA configuration for Traditional SMB
#
# This file contains the global configuration
# plese refer to https://allcloud.atlassian.net/wiki/x/AYDKhwE for more details
# ------------------------------------------------------------------------------------#

homeRegion: eu-west-1
enabledRegions: 
  - eu-west-1
managementAccountAccessRole: AWSControlTowerExecution
cloudwatchLogRetentionInDays: 3653
cdkOptions:
  centralizeBuckets: true
  useManagementAccessRole: true
terminationProtection: false ###NEED TO CHANGE BACK TO TRUE at the end of the deployment #######
controlTower:
  enable: true
  landingZone:
    version: '3.3'
    logging:
      loggingBucketRetentionDays: 365
      accessLoggingBucketRetentionDays: 3650
      organizationTrail: true
    security:
      enableIdentityCenterAccess: true
  controls: []
logging:
  account: LogArchive
  cloudtrail:
    enable: true
    organizationTrail: true
    organizationTrailSettings:
      multiRegionTrail: true
      globalServiceEvents: true
      managementEvents: true
      s3DataEvents: true
      lambdaDataEvents: true
      sendToCloudWatchLogs: true
      apiErrorRateInsight: false
      apiCallRateInsight: false
    accountTrails: []
    lifecycleRules: []
  sessionManager:
    sendToCloudWatchLogs: true
    sendToS3: true
    excludeRegions: []
    excludeAccounts: []
    lifecycleRules: []
    attachPolicyToIamRoles: []
tags:
  - key: "CreateByLZA"
    value: "Yes"
iamRoleSsmParameters: []
backup:
  vaults:
    - name: BackupVault
      deploymentTargets:
        organizationalUnits:
          - Production
