
###################################################################################
# For additional configurable services, features, and property descriptions,      #
# please review our network configuration reference in our README.md:             #
# https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/README.md  #
###################################################################################
homeRegion: &HOME_REGION eu-west-1
#####################################
# Delete default VPCs-- use this    #
# object to delete default VPCs in  #
# any non-excluded accounts         #
#####################################
defaultVpc:
  delete: true
  excludeAccounts: []

centralNetworkServices:
  delegatedAdminAccount: Network
  ipams:
    - name: LZA-ipam
      region: *HOME_REGION
      description: Accelerator IPAM
      operatingRegions:
        - *HOME_REGION
      pools:
        - name: lza-base-pool
          description: Base Pool Ip Adress
          provisionedCidrs:
            - {{R_BASE_POOL_CIDR}}
        - name: lza-core-network-pool
          description: Core network pool
          locale: *HOME_REGION
          provisionedCidrs:
            - {{R_CORE_POOL_CIDR}}



endpointPolicies:
  - name: Default
    document: vpc-endpoint-policies/default.json
  - name: Ec2
    document: vpc-endpoint-policies/ec2.json

#####################################
# Transit Gateways-- use this object #
# to deploy transit gateways         #
#####################################

transitGateways:
  - name: lza-Core-Network
    account: Network
    region: *HOME_REGION
    shareTargets:
      organizationalUnits:
        - Shared-Services
        - Non-Production
        - Production
    asn: 65521
    dnsSupport: enable
    vpnEcmpSupport: enable
    defaultRouteTableAssociation: disable
    defaultRouteTablePropagation: disable
    autoAcceptSharingAttachments: enable
    routeTables:
      - name: Network-Main-Core
        routes: []
      - name: Core-Network-Internet
        routes:
          - destinationCidrBlock: 0.0.0.0/0
            attachment:
              vpcName: LZA-Egress-VPC
              account: Network
####################################
# VPCs-- use this object to deploy  #
# a VPC in a single account and     #
# region.                           #
#####################################

vpcTemplates:
  - name: workload-dmz-template
    deploymentTargets:
      organizationalUnits:
        - Production
        - Non-Production
        - Shared-Services
    region: *HOME_REGION
    ipamAllocations:
      - ipamPoolName: lza-base-pool
        netmaskLength: 22
    internetGateway: true
    transitGatewayAttachments:
      - name: lza-core-network
        transitGateway: 
          name: lza-core-network
        routeTableAssociations:
          - lza-core-network-main
        routeTablePropagations:
          - lza-core-network-main
        subnets:
          - DMZ-Private-A
          - DMZ-Private-B
    natGateways:
      - name: nat-a
        subnet: DMZ-Public-A
      - name: nat-b
        subnet: DMZ-Public-B
    routeTables:
      - name: DMZ-Public-A
        routes:
          - name: Internet
            destination: 0.0.0.0/0
            type: internetGateway
      - name: DMZ-Public-B
        routes:
          - name: Internet
            destination: 0.0.0.0/0
            type: internetGateway
      - name: DMZ-Private-A
        routes:
          - name: NatRoute
            destination: 0.0.0.0/0
            type: natGateway
            target: nat-a
          - name: CoreNetworkRoute
            destination: 10.0.0.0/8
            type: transitGateway
            target: lza-core-network
      - name: DMZ-Private-B
        routes:
          - name: NatRoute
            destination: 0.0.0.0/0
            type: natGateway
            target: nat-b
          - name: CoreNetworkRoute
            destination: 10.0.0.0/8
            type: transitGateway
            target: lza-core-network
    subnets:
      - name: DMZ-Public-A
        availabilityZone: a
        routeTable: DMZ-Public-A
        ipamAllocation:
          ipamPoolName: lza-base-pool
          netmaskLength: 24
      - name: DMZ-Public-B
        availabilityZone: b
        routeTable: DMZ-Public-B
        ipamAllocation:
          ipamPoolName: lza-base-pool
          netmaskLength: 24
      - name: DMZ-Private-A
        availabilityZone: a
        routeTable: DMZ-Private-A
        ipamAllocation:
          ipamPoolName: lza-base-pool
          netmaskLength: 24
      - name: DMZ-Private-B
        availabilityZone: b
        routeTable: DMZ-Private-B
        ipamAllocation:
          ipamPoolName: lza-base-pool
          netmaskLength: 24

  # New workload template with only private subnets
  - name: workload
    deploymentTargets:
      organizationalUnits:
        - Production
        - Non-Production
        - Shared-Services
    region: *HOME_REGION
    ipamAllocations:
      - ipamPoolName: lza-base-pool
        netmaskLength: 22
    internetGateway: false
    transitGatewayAttachments:
      - name: lza-core-network
        transitGateway: 
          name: lza-core-network
        routeTableAssociations:
          - lza-core-network-main
        routeTablePropagations:
          - lza-core-network-main
        subnets:
          - Workload-Private-A
          - Workload-Private-B
    routeTables:
      - name: Workload-Private-A
        routes:
          - name: CoreNetworkRoute
            destination: 10.0.0.0/8
            type: transitGateway
            target: lza-core-network
      - name: Workload-Private-B
        routes:
          - name: CoreNetworkRoute
            destination: 10.0.0.0/8
            type: transitGateway
            target: lza-core-network
    subnets:
      - name: Workload-Private-A
        availabilityZone: a
        routeTable: Workload-Private-A
        ipamAllocation:
          ipamPoolName: lza-base-pool
          netmaskLength: 24
      - name: Workload-Private-B
        availabilityZone: b
        routeTable: Workload-Private-B
        ipamAllocation:
          ipamPoolName: lza-base-pool
          netmaskLength: 24





vpcs:
  - name: workload-dmz
    template: workload-dmz-template

  - name: workload-private
    template: workload

 #Egress-VPC   
  - name: LZA-Egress-VPC
    account: Network
    region: *HOME_REGION
    ipamAllocations:
      - ipamPoolName: lza-core-network-pool
        netmaskLength: 22
    internetGateway: true
    natGateways:
      - name: nat-a
        subnet: Network-EgressPublic-A
      - name: nat-b
        subnet: Network-EgressPublic-B
    routeTables:
      - name: Network-Egress-Public-Tgw-A
        routes:
          - name: TgwRouteCore
            destination: 192.168.0.0/18
            type: transitGateway
            target: lza-Core-Network
          - name: TgwRoute
            destination: 10.0.0.0/8
            type: transitGateway
            target: lza-Core-Network
          - name: Internet
            destination: 0.0.0.0/0
            type: internetGateway
      - name: Network-Egress-Public-Tgw-B
        routes:
          - name: TgwRouteCore
            destination: 192.168.0.0/16
            type: transitGateway
            target: lza-Core-Network
          - name: TgwRoute
            destination: 10.0.0.0/8
            type: transitGateway
            target: lza-Core-Network
          - name: Internet
            destination: 0.0.0.0/0
            type: internetGateway
      - name: Network-Egress-Nat-A
        routes:
          - name: NatRoute
            destination: 0.0.0.0/0
            type: natGateway
            target: nat-a
      - name: Network-Egress-Nat-B
        routes:
          - name: NatRoute
            destination: 0.0.0.0/0
            type: natGateway
            target: nat-b
    subnets:
      - name: Network-EgressTgw-A
        availabilityZone: a
        routeTable: Network-Egress-Nat-A
        ipamAllocation:
          ipamPoolName: lza-core-network-pool
          netmaskLength: 28
      - name: Network-EgressTgw-B
        availabilityZone: b
        routeTable: Network-Egress-Nat-B
        ipamAllocation:
          ipamPoolName: lza-core-network-pool
          netmaskLength: 28
      - name: Network-EgressPublic-A
        availabilityZone: a
        routeTable: Network-Egress-Public-Tgw-A
        ipamAllocation:
          ipamPoolName: lza-core-network-pool
          netmaskLength: 24
      - name: Network-EgressPublic-B
        availabilityZone: b
        routeTable: Network-Egress-Public-Tgw-B
        ipamAllocation:
          ipamPoolName: lza-core-network-pool
          netmaskLength: 24 
    transitGatewayAttachments:
      - name: Network-Egress
        transitGateway:
          name: lza-Core-Network
          account: Network
        routeTableAssociations:
          - Core-Network-Internet
        routeTablePropagations: []
        subnets:
          - Network-EgressTgw-A
          - Network-EgressTgw-B


